"""Manager kit — stand up the recruiting reporting ON YOUR OWN DEVICE.

Interactive: run it in a terminal and answer the questions ("whose data do
you want?" = your managers + their AppStream office ids, which workbook copy
to write, your own ApplicantStream login). Everything it writes stays on THIS
machine:

  ~/.config/recruiting-reporting/roster.json     who to report on
  ~/.config/recruiting-reporting/env.sh          the env the runs need
  <repo>/ownerville-creds.json                   your AppStream login (gitignored)
  manager_run.sh (repo root)                     one command = full refresh
  ~/Library/LaunchAgents/com.recruiting-reporting.daily.plist   (optional)

This kit has NO connection to Alphalete's production runner ("Lucy"), its
command queue, or its schedules — by design (Carlos 2026-09-21). Slack
posting is disabled for your runs (FUNNEL_NO_SLACK=1); failures print to the
log file instead.

  python -m automations.manager_kit.setup
"""
from __future__ import annotations

import getpass
import json
import os
import plistlib
import stat
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CFG_DIR = Path.home() / ".config" / "recruiting-reporting"
LABEL = "com.recruiting-reporting.daily"


def ask(prompt, default=""):
    tail = f" [{default}]" if default else ""
    val = input(f"{prompt}{tail}: ").strip()
    return val or default


def main() -> int:
    print("\n=== Recruiting Reporting — manager setup ===")
    print("Runs entirely on this machine. Nothing here talks to Alphalete's")
    print("runner — your schedule, your login, your workbook.\n")

    sheet_id = ask("1) Your copy of the template — paste the spreadsheet ID\n"
                   "   (the long string in its URL)")
    if not sheet_id or "/" in sheet_id:
        print("   That doesn't look like a bare spreadsheet ID. Re-run when you have it.")
        return 2

    print("\n2) Whose data do you want on the boards?")
    print("   One manager per line. Office id = the number after newOfficeId= in")
    print("   ApplicantStream's office switcher URL; leave it blank if the office")
    print("   doesn't exist yet (the nightly run watches for it and starts pulling")
    print("   automatically). Owner spelling must match the switcher EXACTLY.")
    org = []
    while True:
        name = ask(f"   Manager #{len(org) + 1} display name (blank = done)")
        if not name:
            if org:
                break
            print("   Need at least one manager.")
            continue
        oid = ask(f"     {name}'s AppStream office id (blank = not created yet)")
        owner = ask(f"     {name}'s name as ApplicantStream spells it", default=name)
        org.append([name, oid, owner])
    print(f"   -> {len(org)} manager(s).")

    print("\n3) Your ApplicantStream login (stored ONLY in the gitignored")
    print("   ownerville-creds.json in this repo folder — never committed,")
    print("   never sent anywhere but applicantstream.com).")
    as_user = ask("   ApplicantStream username (spaces matter — type it exactly)")
    as_pass = getpass.getpass("   ApplicantStream password (hidden): ").strip()

    CFG_DIR.mkdir(parents=True, exist_ok=True)
    roster_path = CFG_DIR / "roster.json"
    roster_path.write_text(json.dumps(
        {"org": org, "captainship": [], "south_shore": []}, indent=1),
        encoding="utf-8")
    print(f"\n   wrote {roster_path}")

    creds_path = REPO / "ownerville-creds.json"
    creds = {}
    if creds_path.exists():
        try:
            creds = json.loads(creds_path.read_text())
        except Exception:  # noqa: BLE001
            creds = {}
    creds["appstream_username"] = as_user
    creds["appstream_password"] = as_pass
    creds_path.write_text(json.dumps(creds, indent=1), encoding="utf-8")
    creds_path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    print(f"   wrote {creds_path} (chmod 600)")

    env = {
        "FUNNEL_SSID": sheet_id,
        "INDEED_SOURCE_SPREADSHEET_ID": sheet_id,
        "RECRUITING_ROSTER_JSON": str(roster_path),
        "FUNNEL_NO_SLACK": "1",
    }
    env_sh = CFG_DIR / "env.sh"
    env_sh.write_text("".join(f'export {k}="{v}"\n' for k, v in env.items()),
                      encoding="utf-8")

    runner = REPO / "manager_run.sh"
    runner.write_text(f"""#!/bin/bash
# Recruiting reporting — full refresh on THIS machine (generated by manager_kit).
set -u
cd "{REPO}"
source "{env_sh}"
LOG_DIR="$HOME/.config/recruiting-reporting/logs"; mkdir -p "$LOG_DIR"
STAMP=$(date +%Y%m%d-%H%M)
echo "[manager_run] funnel board..."
PYTHONPATH=. .venv/bin/python -m automations.funnel_board.run "$@" \\
  2>&1 | tee "$LOG_DIR/funnel-$STAMP.log"
echo "[manager_run] indeed source report..."
PYTHONPATH=. .venv/bin/python -m automations.indeed_source_report.run \\
  2>&1 | tee "$LOG_DIR/indeed-$STAMP.log"
echo "[manager_run] done."
""", encoding="utf-8")
    runner.chmod(0o755)
    print(f"   wrote {runner}")

    print("\n4) Google access: this machine's Google credential must be able to")
    print("   EDIT your workbook copy. Testing the connection now...")
    os.environ.update(env)
    try:
        from automations.funnel_board.auth import session
        S = session()
        r = S.get("https://sheets.googleapis.com/v4/spreadsheets/%s"
                  "?fields=properties(title)" % sheet_id, timeout=30)
        r.raise_for_status()
        print("   OK — can read: %s" % r.json()["properties"]["title"])
    except Exception as e:  # noqa: BLE001
        print("   NOT YET: %s" % str(e)[:160])
        print("   Fix: share the workbook (Editor) with the Google account this")
        print("   machine authenticates as, or set up the OAuth token / service")
        print("   account per the repo README, then re-run this setup.")

    if ask("\n5) Install a daily schedule on this Mac (1:00 AM + 1:00 PM)? y/n",
           default="y").lower().startswith("y"):
        plist = {
            "Label": LABEL,
            "ProgramArguments": ["/bin/bash", str(runner)],
            "StartCalendarInterval": [
                {"Hour": 1, "Minute": 0}, {"Hour": 13, "Minute": 0}],
            "StandardOutPath": str(CFG_DIR / "logs" / "launchd.log"),
            "StandardErrorPath": str(CFG_DIR / "logs" / "launchd.log"),
        }
        pdir = Path.home() / "Library" / "LaunchAgents"
        pdir.mkdir(parents=True, exist_ok=True)
        ppath = pdir / f"{LABEL}.plist"
        with open(ppath, "wb") as f:
            plistlib.dump(plist, f)
        subprocess.run(["launchctl", "unload", str(ppath)],
                       capture_output=True)
        subprocess.run(["launchctl", "load", str(ppath)], capture_output=True)
        print(f"   installed {ppath} (1:00 AM + 1:00 PM daily)")
    else:
        print("   skipped — run ./manager_run.sh whenever you want a refresh.")

    print("\nDone. First run (draws everything, ~5-15 min):")
    print("   ./manager_run.sh")
    print("Then once, for history:   ./manager_run.sh --weeks 34")
    print("(With many managers, batch history: --weeks 34 --only \"A|B|C\")")
    return 0


if __name__ == "__main__":
    sys.exit(main())
