"""Zero Streak screenshots — the escalating 'zeros in a row' callout (Carlos 7/23).

Replaces the VA's manual pass (Jolie's 5:41am "Zero-Sales 7.22" post): she clears
the board's filters, keeps only reps who rolled a literal 0 yesterday, screenshots
it, then adds the prior day to the filter and screenshots again, and again.

TWO differences from how she posts it today, both from Carlos's 7/23 Loom:
  * she ships ONE image per campaign per level (8 files under a 3-bullet caption);
    he asked for it "organized by campaign" in a SINGLE image per level — the rows
    are already colour-coded by campaign, so one grouped image reads the same and
    turns 8 unlabelled files into a few labelled thread replies.
  * each level gets its own reply with its own caption, so a level can be reacted
    to / replied to on its own.

WHAT COUNTS AS A ZERO: a literal numeric 0 for that day. 'X'/'x' (didn't work),
'T' (terminated) and blank (no data) are NOT zeros — you can't roll a zero on a day
you didn't sell. Reconciled against the board's own counter: on the 7.26 week the
sheet's "AT&T (B2B) — Rolled a Zero" reads 7 for Monday, and there are exactly 7
B2B rep rows carrying a literal 0 in the Monday column.

SUNDAY (Megan 7/23, same rule as the D2D zeros): Sunday is not a mandatory work
day, so it never counts as a zero and never appears as a column — BUT a Sunday
SALE still breaks the run. So walking back from the anchor, a Sunday is invisible
unless the rep put up a positive number on it, in which case the streak stops
there. Sunday is likewise never the anchor: on a Monday run (yesterday = Sunday)
we anchor on Saturday.

STREAKS CROSS WEEKS (Megan 7/23) — up to MAX_DAYS selling days back. The board only
ever holds ONE week, so earlier days come from the `WeekData` tab, which archives
every week keyed `"<REP>|<WE m.d>"` with Mon..Sun across columns B..H (32 weeks of
history as of 7/23). Those keys are generated by the board's own day formulas
(=INDEX(WeekData…MATCH($B5&"|"&$B$2))), so the board's REP cell IS the key — no
alias translation needed. A rep with no history for a week (a new hire) simply
can't extend past it, which truncates the streak rather than overstating it.

WE DO NOT FLIP THE GOLD WEEK CELL to read a past week, even on a throwaway copy:
only SOME day cells are formulas keyed on B2 — on the 7.26 week Mon..Thu are
hand-typed literals and only Fri..Sun are still =INDEX(WeekData…) — so flipping
the selector repopulates a few cells and leaves stale typed numbers behind,
producing a mixed-week board. Reading WeekData directly is the only safe path.

OWN THROWAWAY TAB: this builds a second copy of the Sales Board rather than
sharing the boards' one, because it OVERWRITES the day columns with the borrowed
cross-week window. That would corrupt the boards' render if they shared a tab, and
it keeps column A's rep numbers pristine (render_all renumbers them to a 1..N
rank). The day cells are conditionally formatted on value (=AND(ISNUMBER(E5),E5=0)
-> pink, ="X" -> grey), so a borrowed day recolours itself correctly — which is
also why the window has to be written into E..K and nowhere else.
"""
from __future__ import annotations

import datetime as dt
import re
import time
from pathlib import Path

from gspread.utils import rowcol_to_a1

from automations.recruiting_report.fill import _retry
from automations.sales_boards import render as R

TMP_TAB = "_sb_zeros_tmp"
WEEK_DATA_TAB = "WeekData"
MAX_DAYS = 7                 # Megan 7/23: go past 3, up to a week of selling days
LOOKBACK_CAL_DAYS = 12       # calendar reach that safely contains MAX_DAYS + Sundays
DAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
CAMPAIGN_COL = R.CAMPAIGN_COL          # col L — the grouping key
LAST_SHOWN_COL = "L"                   # crop through Campaign
CURRENT_WEEK_COL = R.CURRENT_WEEK_COL  # col C — frozen before we touch the days
STREAK_COL = 23                        # col W — blank across every rep row; see below
EMOJI = ":no_entry_sign:"


def is_zero(v) -> bool:
    """A literal numeric zero — '0', '0.0', '0.00'. Not X / T / blank."""
    return bool(re.fullmatch(r"0(\.0+)?", str(v).strip()))


def is_sale(v) -> bool:
    """A positive number — the only thing that breaks a streak on a Sunday."""
    try:
        return float(str(v).strip()) > 0
    except (TypeError, ValueError):
        return False


def _norm(s) -> str:
    """Fallback key: parenthetical suffixes dropped, whitespace collapsed, cased
    down. Used only if the exact board name misses in WeekData."""
    return re.sub(r"\s+", " ", re.sub(r"\([^)]*\)", "", str(s))).strip().lower()


def anchor_day(yday: dt.date) -> dt.date:
    """The most recent day a zero can be rolled on. Sunday isn't a work day, so a
    Monday run (yesterday = Sunday) anchors on Saturday instead."""
    return yday - dt.timedelta(days=1) if yday.weekday() == 6 else yday


def mandatory_days(anchor: dt.date, n: int) -> list:
    """The n most recent SELLING days ending on `anchor`, OLDEST FIRST, skipping
    Sundays. Walks straight through week boundaries — that's the whole point.
    These are the days that get counted and shown as columns."""
    out, d = [], anchor
    while len(out) < n:
        if d.weekday() != 6:
            out.append(d)
        d -= dt.timedelta(days=1)
    return list(reversed(out))


def we_label(d: dt.date) -> str:
    """'M.D' of the SUNDAY ending d's Mon-Sun week — the board's gold-cell format
    and the WeekData key suffix."""
    sun = d + dt.timedelta(days=(6 - d.weekday()) % 7)
    return f"{sun.month}.{sun.day}"


def load_week_data(sh) -> tuple:
    """(exact, normalized) lookups: {(name, 'M.D'): [Mon..Sun]}. Two indexes so a
    minor spelling drift still resolves, without letting it mask a real miss."""
    g = _retry(lambda: sh.worksheet(WEEK_DATA_TAB).get_all_values())
    exact, norm = {}, {}
    for row in g[1:]:
        key = (row[0] if row else "").strip()
        if "|" not in key:
            continue
        name, wk = key.rsplit("|", 1)
        days = [(row[i] if i < len(row) else "") for i in range(1, 8)]
        exact[(name.strip(), wk.strip())] = days
        norm[(_norm(name), wk.strip())] = days
    return exact, norm


def level_label(n: int) -> str:
    """'1 Day' / '2 Days' / '3 Days' … — one consistent series, so the thread reads
    as one escalating set however deep it goes (Megan 7/23: not '1 day 0')."""
    return f"{n} Day" if n == 1 else f"{n} Days"


def plain_caption(n: int, tag: str) -> str:
    """Caption text WITHOUT the emoji — the dedupe needle, since Slack may store
    an emoji as a shortcode or as the rendered character."""
    return f"Zero Streak {tag} — {level_label(n)}"


def title_for(n: int, days: list) -> str:
    """days = the shown window, oldest first; level n uses its last n."""
    span = days[-n:]
    end = span[-1]
    if n == 1:
        where = f"{end.strftime('%A')} {end.month}/{end.day}"
    else:
        start = span[0]
        where = (f"{start.strftime('%a')} {start.month}/{start.day} → "
                 f"{end.strftime('%a')} {end.month}/{end.day}")
    return f"Zero Streak: {level_label(n)}  ({where})"


def rep_values(g, row, dates, board_we, exact, norm, board_day_col) -> tuple:
    """({date: value}, missing_weeks) for one rep over a span of CALENDAR dates —
    Sundays included, because a Sunday sale has to be visible to the walk.

    Current-week days come off the BOARD (they're hand-typed there and can be
    fresher than WeekData, which carries no row for the open week at all); earlier
    days come from WeekData. `missing_weeks` names past weeks we had no row for, so
    a truncated streak is explainable rather than silent.
    """
    name = R.cell(g, row, R.NAME_COL).strip()
    vals, missing = {}, []
    for d in dates:
        wk = we_label(d)
        if wk == board_we:
            vals[d] = R.cell(g, row, board_day_col[d.weekday()])
            continue
        rec = exact.get((name, wk)) or norm.get((_norm(name), wk))
        if rec is None:
            vals[d] = ""
            missing.append(wk)
        else:
            vals[d] = rec[d.weekday()]
    return vals, sorted(set(missing))


def walk_streak(vals: dict, anchor: dt.date, cap: int) -> int:
    """Consecutive zeros ending on the anchor, walking back day by day.

    Sunday is transparent — it adds nothing to the count, but a Sunday SALE stops
    the walk (Megan 7/23). Any other non-zero (a sale, an 'X', a 'T', or a day we
    have no data for) stops it too.
    """
    n, d = 0, anchor
    while n < cap:
        v = vals.get(d, "")
        if d.weekday() == 6:
            if is_sale(v):
                break
            d -= dt.timedelta(days=1)
            continue
        if not is_zero(v):
            break
        n += 1
        d -= dt.timedelta(days=1)
    return n


def render_zeros(sh, src_ws, sheet_id, token, yday, out_dir: Path) -> dict:
    """Build one image per streak depth. Returns {level: {"path", "reps",
    "campaigns"}} — empty if nobody rolled a zero on the anchor day.

    Creates and deletes its own throwaway tab; the live board is never touched.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    g = _retry(src_ws.get_all_values)
    ts, _te = R.totals_range(g)
    first, last = R.rep_region(g, ts)
    board_we = R.cell(g, 2, 2).strip()

    anchor = anchor_day(yday)
    days = mandatory_days(anchor, MAX_DAYS)        # shown columns, oldest first
    span = [anchor - dt.timedelta(days=i) for i in range(LOOKBACK_CAL_DAYS)]  # incl. Sundays
    board_day_col = {}
    for wd, nm in enumerate(DAY_NAMES):
        c = R.day_column(g, nm)
        if c is None:
            raise SystemExit(f"no '{nm}' column on the board "
                             f"(row {R.DAY_HEADER_ROW} renamed?)")
        board_day_col[wd] = c

    exact, norm = load_week_data(sh)
    print(f"  zeros: window {days[0]:%a %m/%d} → {days[-1]:%a %m/%d} "
          f"({len(days)} selling days, Sundays skipped; board week = {board_we})")

    rows = [r for r in range(first, last + 1)
            if R.cell(g, r, R.NAME_COL).strip()
            and R.cell(g, r, CAMPAIGN_COL).strip() in R.PROGRAMS]
    window, streaks, gaps = {}, {}, {}
    for r in rows:
        if R.is_terminated(g, r):
            # Terminated reps are off the board (the Sales Boards drop them too).
            window[r], streaks[r] = ["T"] * len(days), 0
            continue
        vals, miss = rep_values(g, r, span, board_we, exact, norm, board_day_col)
        window[r] = [vals[d] for d in days]
        streaks[r] = walk_streak(vals, anchor, MAX_DAYS)
        if miss:
            gaps[R.cell(g, r, R.NAME_COL).strip()] = miss

    if not any(streaks.values()):
        print("  zeros: nobody rolled a zero on the anchor day — no images")
        return {}
    if gaps:
        # Not an error: almost always a new hire with no history. Surfaced so a
        # streak that stops early is explainable (STANDING: flag non-matches).
        names = sorted(gaps)
        print(f"  zeros: {len(names)} rep(s) have no WeekData for part of the window, "
              f"so their streak stops there: "
              f"{', '.join(names[:6])}{' …' if len(names) > 6 else ''}")

    for w in sh.worksheets():                  # sweep an orphan from a crashed run
        if w.title == TMP_TAB:
            sh.del_worksheet(w)
    tmp = sh.duplicate_sheet(src_ws.id, new_sheet_name=TMP_TAB)
    gid, width = tmp.id, tmp.col_count
    result = {}
    try:
        sh.batch_update({"requests": [{"clearBasicFilter": {"sheetId": gid}}]})
        cols = [R.FIRST_DAY_COL + i for i in range(len(days))]
        c0, c1 = _letter(cols[0]), _letter(cols[-1])
        sc = _letter(STREAK_COL)
        rng = list(range(first, last + 1))

        tmp.batch_update([
            # Freeze Current Week BEFORE overwriting the days — col C is =SUM(E:K),
            # so a cross-week window would otherwise silently redefine it.
            {"range": f"C{first}:C{last}",
             "values": [[R.cell(g, r, CURRENT_WEEK_COL)] for r in rng]},
            # Dated headers: two Wednesdays in one window only tell apart by date.
            {"range": f"{c0}{R.DAY_HEADER_ROW}:{c1}{R.DAY_HEADER_ROW}",
             "values": [[f"{d.strftime('%a')} {d.month}/{d.day}" for d in days]]},
            {"range": f"{c0}{first}:{c1}{last}",
             "values": [window.get(r, [""] * len(days)) for r in rng]},
            # The streak can't be recomputed from the shown cells (a Sunday sale
            # breaks a run without being a column), so park it in a blank column
            # well right of the export — sortRange carries it with its row, which
            # is how it survives the regroup below.
            {"range": f"{sc}{first}:{sc}{last}",
             "values": [[streaks.get(r, 0)] for r in rng]},
        ], value_input_option="USER_ENTERED")

        # Day columns past the window still hold this week's leftovers — hide them.
        R.set_cols_hidden(sh, gid, [c for c in range(R.FIRST_DAY_COL, R.LAST_DAY_COL + 1)
                                    if c not in cols], True)
        # Group by campaign, then alphabetical inside it — the row fills are already
        # colour-coded per campaign, so grouping makes the blocks read at a glance.
        R.sort_region(sh, gid, first, last, [(CAMPAIGN_COL, True), (R.NAME_COL, True)], width)

        g2 = _retry(tmp.get_all_values)
        scored = {r: int(R.cell(g2, r, STREAK_COL) or 0) for r in rng}

        # Levels are nested (everyone at n+1 is also at n), so a level whose roster
        # is identical to the next one deeper says strictly less than that one —
        # post only the deeper. Without this, one rep on a 7-day run would ship
        # four near-identical images (4/5/6/7 Days). Jolie does the same by hand:
        # her 7.22 post has no BOX 3-day image because it duplicated her BOX 2-day.
        rosters = {}
        for n in range(1, len(days) + 1):
            keep = {r for r, s in scored.items() if s >= n}
            if not keep:
                print(f"  zeros: nobody at {n} in a row — deepest level is {n - 1}")
                break
            rosters[n] = keep
        emit = [n for n in sorted(rosters) if rosters.get(n + 1) != rosters[n]]
        folded = [n for n in sorted(rosters) if n not in emit]
        if folded:
            print(f"  zeros: level(s) {', '.join(map(str, folded))} have the same reps "
                  f"as a deeper level — folded into it, not posted twice")

        for n in emit:
            keep = rosters[n]
            # show exactly the n days called out — the rightmost n of the window
            older = cols[:len(days) - n]
            R.set_cols_hidden(sh, gid, older, True)
            hide = [r for r in rng if r not in keep]
            R.set_rows_hidden(sh, gid, hide, True)
            # Rank the VISIBLE rows 1..N (Megan 7/23). Column A holds each rep's own
            # board number, so a filtered view would otherwise show jumps (18, 20,
            # 10, 21 …). Same helper the Sales Boards use.
            R.renumber(tmp, first, last, keep)
            # Header is exported per level, INSIDE the column hiding — exporting it
            # once up front gave it all 7 day columns while the body had n, so the
            # two didn't line up and Campaign sat under the wrong heading.
            header = R.export(sheet_id, gid,
                              f"A{R.DAY_HEADER_ROW}:{LAST_SHOWN_COL}{R.DAY_HEADER_ROW}", token)
            body = R.export(sheet_id, gid,
                            f"A{min(keep)}:{LAST_SHOWN_COL}{max(keep)}", token)
            w = max(header.width, body.width)
            img = R.stitch([R.title_bar(w, title_for(n, days)), header, body])
            path = out_dir / f"Zeros ({n}).png"
            img.save(path)
            camps = sorted({R.cell(g2, r, CAMPAIGN_COL).strip() for r in keep})
            result[n] = {"path": path, "reps": len(keep), "campaigns": camps}
            print(f"  zeros L{n}: {len(keep):2} reps ({', '.join(camps)}) -> {path.name}")
            R.set_rows_hidden(sh, gid, hide, False)
            R.set_cols_hidden(sh, gid, older, False)
            time.sleep(1.2)
    finally:
        sh.del_worksheet(tmp)
        print("  zeros temp tab removed")
    return result


def _letter(c: int) -> str:
    return rowcol_to_a1(1, c)[:-1]
